language: node_js
cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
    - ~/.cache
node_js:
  - '8'
  - '10'
env:
  - TEST_SUITE="test:unit"
  - TEST_SUITE="test:e2e:ci"
install:
  - yarn bootstrap
script:
  - yarn test-ci
notifications:
  email: false
git:
  depth: 5
