jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)

  - script: |
      ${{ parameters.preScript }}
      node --version
      npm --version
      yarn --version
      yarn
      yarn bootstrap
      ${{ parameters.script }}
    env:
      CYPRESS_RECORD_KEY: $(CYPRESS_RECORD_KEY)
